let venues = [
	{
		value: "Celebration Banquet Hall",
		address: "Karamtoli Rd, Morabadi",
		city: "Ranchi",
		ratings: 4.3,
		capacity: "900-1000",
		veg: 1200,
		nonveg: 1600,
		display: "/form/venues/celebration.jpg",
	},
	{
		value: "Swagatam Banquet Hall",
		address: "Harmu Housing Colony, Vasant Vihar",
		city: "Mumbai",
		ratings: 4.1,
		capacity: "600-700",
		veg: 1000,
		nonveg: 1400,
		display: "/form/venues/swagatam.jpg",
	},
	{
		value: "Manya Palace",
		address: "Tetartoli, Morabadi",
		city: "Jaipur",
		ratings: 3.9,
		capacity: "500-600",
		veg: 900,
		nonveg: 1200,
		display: "/form/venues/manya.jpg",
	},
	{
		value: "Amaltash Banquet Hall",
		address: "Karamtoli Rd, Morabadi",
		city: "Delhi",
		ratings: 4.3,
		capacity: "300-400",
		veg: 1000,
		nonveg: 1500,
		display: "/form/venues/amaltash.jpg",
	},
	{
		value: "Krishna Palace",
		address: " St. Anne Lane, Tharpakhna",
		city: "Bokaro",
		ratings: 3.6,
		capacity: "150-250",
		veg: 500,
		nonveg: 800,
		display: "/form/venues/krishna.jpg",
	},
	{
		value: "Aangan Palace",
		address: "Chutia-Namkum Rd, New Makchund Toli",
		city: "Indore",
		ratings: 4.0,
		capacity: "200-300",
		veg: 800,
		nonveg: 1300,
		display: "/form/venues/aangan.jpg",
	},
	{
		value: "Paahi Palace",
		address: "Football stadium-20, Morabadi",
		city: "Nagpur",
		ratings: 4.1,
		capacity: "200-300",
		veg: 1000,
		nonveg: 1400,
		display: "/form/venues/paahi.jpg",
	},
	{
		value: "Raj Mahal Marriage Home",
		address: "1626/B10 Shantman Nagar Road",
		city: "Bangalore",
		ratings: 4.0,
		capacity: "400-500",
		veg: 800,
		nonveg: 1300,
		display: "/form/venues/rajmahal.jpg",
	},
	{
		value: "Sohrai Bhawan",
		address: "Harmu Housing Colony, Delatoli",
		city: "Lucknow",
		ratings: 4.1,
		capacity: "700-800",
		veg: 800,
		nonveg: 1300,
		display: "/form/venues/soharibhawan.jpg",
	},
	{
		value: "Dharamsala Marriage Hall",
		address: "13, N Market Rd, Upper Bazar",
		city: "Patna",
		ratings: 3.4,
		capacity: "200-300",
		veg: 600,
		nonveg: 900,
		display: "/form/venues/dharmshala.jpg",
	},
];

export default venues;
